name: Run install and build on new PRs
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Checkout-and-Install-Dependencies:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: namestone_test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event. The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Run tests
        # env:
          # TEST_DATABASE_BASE="postgresql://admin:admin@localhost:5432"
          # TEST_DATABASE_URL: postgresql://admin:admin@localhost:5432/namestone_test
          # TEST_DB_NAME: namestone_test
          # TEST_API_KEY: fake-test-api-key
        run: yarn test

      - name: Build Next.js application
        env:
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: "some-random-project-id"
        run: yarn build

      - run: echo "🍏 This job's status is ${{ job.status }}."
